### ISSUE TITLE
Referenciar 'country' como foreign key

### ISSUE THREAD

**Issue by pvguerra** [blitsoftwares/laravel-states-and-cities#1]
Após seguir todos os passos do README, tentei referenciar um país a um usuário e o seguinte erro apareceu. Como se a migration não existisse, mas pelo que entendi o pacote já cria tudo.

> Illuminate\Database\QueryException  : SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "countries" does not exist (SQL: alter table "users" add constraint "users_country_id_foreign" foreign key ("country_id") references "countries" ("id"))

```php
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('cpf')->unique();
            $table->string('phone');
            $table->string('phone2')->nullable();
            $table->integer('country_id')->unsigned();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });

        Schema::table('users', function (Blueprint $table){
            $table->foreign('country_id')->references('id')->on('countries');
        });
```

**Comment by blitsoftwares** [comment]
Ola @pvguerra !

Desculpe a demora, por algum motivo não recebemos a notificação da sua issue. 
De qualquer forma, segue um exemplo de implementação.

1) na sua migrate adicione os campos de address completo:
```
(...)
$table->string('postal_code')->nullable();
$table->string('street')->nullable();
$table->string('number')->nullable();
$table->string('district')->nullable();
$table->string('complement')->nullable();
$table->integer('country_id')->nullable();
$table->integer('state_id')->nullable();
$table->integer('city_id')->nullable();
```

2) na Model adicione os campos em $fillable []
```
(...)
'postal_code',
'street',
'number',
'district',
'complement',
'country_id',
'state_id',
'city_id',
```

3) na Model adicione o relacionamento:
```
(...)
public function city()
{
  return $this->belongsTo(City::class);
}
```

Agora voce tem os relacionamentos completo por exemplo:

Cidade: $obj->city->name
Estado: $obj->city->state->name
Pais: $obj->city->state->country->name

4) na sua View de cadastro, apenas chame o form no seu html
```
<h4>Endereço</h4>
@include('StatesAndCities::addresses.fields')
```

Se você publicou os arquivos, voce pode personalizar este formulário de acordo com seu layout em resources/views/vendor/StatesAndCities 

Se os JS estiverem implementados, deve estar tudo rodando.

Conseguiu resolver?
